The files train.csv and test.csv contain all the training samples as comma-sparated values. There are 3 columns in them, corresponding to class index (1 to 4), title and description. The title and description are escaped using double quotes ("), and any internal double quote is escaped by 2 double quotes (""). New lines are escaped by a backslash followed with an "n" character, that is "\n".

In [20]:
import pandas as pd 

# load dataset 
train_path= "../data/raw/train.csv"

df=pd.read_csv(train_path)

df.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

02- Data preproceess

In [21]:
df["text"]= df["Title"] + " " + df["Description"]

df["label"] = df["Class Index"]-1 #pytorch takes indx from 0

df= df[["text","label"]]
df.head(10)

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2
5  Stocks End Up, But Near Year Lows (Reuters) Re...      2
6  Money Funds Fell in Latest Week (AP) AP - Asse...      2
7  Fed minutes show dissent over inflation (USATO...      2
8  Safety Net (Forbes.com) Forbes.com - After ear...      2
9  Wall St. Bears Claw Back Into the Black  NEW Y...      2

In [22]:
df["text"] = df["text"].str.replace("\\n", " ", regex=True)
df["text"] = df["text"].str.strip()

In [23]:

df.head(10)

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      2
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3  Iraq Halts Oil Exports from Main Southern Pipe...      2
4  Oil prices soar to all-time record, posing new...      2
5  Stocks End Up, But Near Year Lows (Reuters) Re...      2
6  Money Funds Fell in Latest Week (AP) AP - Asse...      2
7  Fed minutes show dissent over inflation (USATO...      2
8  Safety Net (Forbes.com) Forbes.com - After ear...      2
9  Wall St. Bears Claw Back Into the Black  NEW Y...      2